name: run-tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.3, 8.4]
        laravel: [11.*, 12.*]
        include:
          - laravel: 11.*
            testbench: ^9.0
          - laravel: 12.*
            testbench: ^10.0
      fail-fast: false

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, dom, fileinfo
          tools: composer:v2

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ matrix.php }}-${{ matrix.laravel }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
          composer update --prefer-dist --no-interaction --prefer-stable

      - name: Run tests
        run: vendor/bin/pest
